#+TITLE: README file for thesis-eagerm
#+DATE:
#+AUTHOR: Michael A Eager
#+EMAIL: mick.eager@gmail.com
# 

* README

To clone this repo, be sure to grab the added submodules:
#+BEGIN_SRC sh
git clone --recursive https://github.com/maeager/thesis-eagerm
#+END_SRC
or, if you forgot, use:
#+BEGIN_SRC sh
git submodule update --init --recursive
#+END_SRC

Super-repo to grab my PhD manuscript from chapters in subrepos: 
  - org-manuscript,
  - LiteratureReview,
  - MethodsChapter, 
  - SimpleResponsesChapter,  
  - VowelProcessingChapter, and
  - GAChapter. 

The final manuscript PDF is generated in _org-manuscript_.

To compile and generate the manuscript, run:
#+BEGIN_SRC sh
make all
#+END_SRC

For dependencies and other comments read the README file in org-manuscript and 
SimpleResponsesChapter.

* Licence

Copyright 2008-2014 Michael Eager (mick.eager@gmail.com).

The thesis-eagerm package is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

The thesis-eagerm package is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with the thesis-eagerm source code. If not, see http://www.gnu.org/licenses/.
