#+TITLE: README file for thesis-eagerm
#+DATE:
#+AUTHOR: Michael A Eager
#+EMAIL: mick.eager@gmail.com
# -*- mode: org-mode -*

* README

Super-repo to compile PhD manuscript from chapters in subrepos: GAChapter, 
LiteratureReview, MethodsChapter, SimpleResponsesChapter, and VowelProcessingChapter. 

The final manuscript PDF is generated in _org-manuscript_.

To compile and generate the manuscript, run 'make all'.

For dependencies and other comments read the README file in org-manuscript and 
SimpleResponsesChapter.

* Licence

Copyright 2008-2014 Michael Eager (mick.eager@gmail.com).

The thesis-eagerm package is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

The thesis-eagerm package is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with the thesis-eagerm source code. If not, see http://www.gnu.org/licenses/.
